### ISSUE TITLE
既存アプリケーション開発で追加したい機能

### ISSUE THREAD

**Issue by kimuray** [DiveintoCode-corp/diveintopost#1]
## 概要
既存アプリケーション開発を就業コースに加えるにあたり、アプリケーションの作り込みが必要です。
作り込みにあたり、あると便利そうなクオリティが上がりそうな機能を列挙していきましょう。

**Comment by kimuray** [comment]
コメントに思いついた機能を追加していく感じで！

**Comment by lasershow** [comment]
- 検索機能
- テンプレート機能
- メンション機能
- 通知機能

https://teams.qiita.com/features/

**Comment by shibatadaiki** [comment]
チーム機能・チーム招待機能
カテゴリ機能
JSでのサイドバー
ファイルアップロード
markdownでの記述

**Comment by kimuray** [comment]
課金(チーム単位)
課金状態管理
タグのサジェスト機能

**Comment by shibatadaiki** [comment]
コメント機能
最低限のセキュリティ

**Comment by shibatadaiki** [comment]
気持ち良いデザイン

**Comment by shibatadaiki** [comment]
コメント編集

**Comment by tominagashuji** [comment]
画像投稿（ユーザー、コメント）

**Comment by tominagashuji** [comment]
エラーメッセージ（ブランク投稿で画面に変化なし）
