### ISSUE TITLE
議題を示すモデルを作成する

### ISSUE THREAD

**Issue by kimuray** [DiveintoCode-corp/diveintopost#2]
## 概要
議題を示すモデルを作成する。
会議ではAgendaという名前のmodelだったやつ。
Agendaはラテン語のようなので別のいい感じの単語求む。

## 対応内容
- [ ] 議題用モデルを作成する
  * カラムとしてはtitle, descriptionとuser_id
- [ ] userとteamとアソシエーションを設定する

**Comment by tominagashuji** [comment]
read.me を見直し git clone し直し。

**Comment by tominagashuji** [comment]
再度rails db:migrate db:create 実施
エラー：
rbenv: rails: command not found
The `rails' command exists in these Ruby versions:
  2.3.0
  2.4.1
くそー。

**Comment by kimuray** [comment]
プロジェクトルートで`bin/rails`とするか`bundle exec rails`とするかgem install railsでrailsインストールしちゃうかで解決できそうです！

**Comment by tominagashuji** [comment]
https://qiita.com/4geru/items/1354bb1d5b2df715a5e2 
前回のURLと木村さんの提言にて解消。（木村さんありがとうございます〜！）
sudo gem install rails 
bundle install
まで正常終了。
その後rails s にてアプリ起動するもエラー。
ブートストラップ関係のエラー。
tominagashuujinoMacBook-Air:diveintopost tominagashuuji$ rails s
=> Booting Puma
=> Rails 5.2.0 application starting in development 
=> Run `rails server -h` for more startup options
========================================
  Your Yarn packages are out of date!
  Please run `yarn install` to update.
========================================
To disable this check, please add `config.webpacker.check_yarn_integrity = false`
to your Rails development config file (config/environments/development.rb).
yarn check v1.3.2
error Couldn't find an integrity file
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
Exiting

**Comment by tominagashuji** [comment]
sudo gem install bundle
bundle install
rails s で yarn のエラー発生
yarn install 
rails s でエラー
そもそも bundle install --path vendor/bundle でbundle install をしてなかったので再実施
rails db:create db:migrate
実施するもエラー。devise_keyが無いとの事。
config/initiraizer/devise.rbにて表示されたkey を入力。
rails db:create db:migrate が正常終了
rails s にてアプリ起動確認

**Comment by tominagashuji** [comment]
add commit push を実施するもpush不可。
