### ISSUE TITLE
アジェンダの削除機能を実装すること（紐づいている記事も削除し、そのアジェンダのチームに属しているメンバー全員に通知メールを送信すること）/Implement the agenda delete function（ Delete the article associated with the agenda and send a notification email to all members in the team）

### ISSUE THREAD

**Issue by shibatadaiki** [diveintocode-corp/diveintopost#67]
現状サイドバーに表示される各アジェンダを削除する機能がないので、その機能を追加してほしい。

`以下の要件で作成されることを想定している`

```
AgendasControllerのdestroyアクションを追加し、そこに機能追加する
Agendaの名前の右の部分に削除ボタンを作成し、そのボタンを押すとそのAgendaが削除される
Agendaに紐づいているarticleも一緒に削除される
Agendaを削除できるのは、そのAgendaの作者もしくはそのAgendaに紐づいているTeamの作者（オーナー）のみ
Agendaが削除されると、そのAgendaに紐づいているTeamに所属しているユーザー全員に通知メールが飛ぶ
情報処理が完了した後はDashBoardに飛ぶ
その他、アプリケーションの挙動に不審な点やエラーがないこと
```

![2018-12-02 20 31 08](https://user-images.githubusercontent.com/25131575/49339183-66b9f380-f671-11e8-9714-23ff84f3c9da.png)

**その他、質問や確認事項などがあれば別途課題投稿欄のコメントで質問すること**

**今回テストは不要**

### Meet the following requirements.

- Add the destroy action of AgendasController and then add function to it.
- Create a delete button in the right part of Agenda name and press that button to delete Agenda.
- Agenda articles associated with Agenda is also deleted.
- Agenda can only be deleted by the creator of the Agenda or the creator (owner) of the team associated with the Agenda.
- When an agenda is deleted, a notification email is sent to all users on the team associated with that agenda. Go to DashBoard after the processing is complete.
- check the behavior of the application.

[![Image from Gyazo](https://t.gyazo.com/teams/diveintocode/bdd89bfdc31a1d02e76c241695945dfd.png)](https://diveintocode.gyazo.com/bdd89bfdc31a1d02e76c241695945dfd)

**Comment by anselmehado** [comment]
https://github.com/anselmehado/DevelopInTeam.git
