### ISSUE TITLE
記事(article)をマークダウンで表示できるようにする

### ISSUE THREAD

**Issue by kimuray** [DiveintoCode-corp/diveintopost#7]
## 概要
記事を表示する時にマークダウンで表示できるようにする

## 対応内容
- [x] マークダウン関連のgemを導入する
- [x] articleのshow画面でマークダウンの表示をできるようにする

## RubyのMarkdownパーサー主なやつ
* https://github.com/vmg/redcarpet
* https://github.com/increments/qiita-markdown
* https://github.com/gettalong/kramdown

**Comment by tominagashuji** [comment]
環境作成
git pull origin develop
git checkout -b feature/issues-07

必要なgemの導入
gem 'redcarpet', '~> 2.3.0'
gem 'coderay'
bundle install
参考URL：https://qiita.com/hkengo/items/978ea1874cf7e07cdbfc

一度この辺りで push してみる

**Comment by tominagashuji** [comment]
実装に着手。
参考URLを真似してみる。ヘルパーに記述。
rails s で起動。/articles/new で動作確認するもコケる。
パラメータを上手く設定出来てない？
参考URL
https://teratail.com/questions/61224
https://teratail.com/questions/47152
https://teratail.com/questions/13525
https://programming-beginner-zeroichi.jp/articles/45

**Comment by tominagashuji** [comment]
routesファイルをみるとルーティングが階層構造になっているので /teams/articles/new で行ける！
アクセスするもルーティングエラー。、、、なんでや？rails routesでちゃんと確認しよう。
自分のアプリで階層ルーティングのコンファームを見る。
Prefix Verb   URI Pattern                  Controller#Action
confirm_events POST   /events/confirm(.:format)    events#confirm
自分のはこんな感じ。
new_team_article GET    /teams/:team_id/articles/new(.:format)    articles#new
DIPはこんな感じ。真似する。
/teams/1/articles/new にアクセス。。。出来た！！

**Comment by tominagashuji** [comment]
木村さんと相談後、routes.rb を変更。article作成画面へは以下のパスで。
/agendas/:agenda_id/articles/new → /agendas/1/articles/new
案の定、Couldn't find Agenda with 'id'=1 というid系で落ちる。調査開始。

**Comment by tominagashuji** [comment]
開発方針の確認（木村さんに相談）
DIP起動→Articleを新規作成をする（/agendas/:agenda_id/articles/new）→Agenda_idが必要なのでagendaレコードは作成しておく（コンソールで済）→Article_new画面を作成→Article_show画面でマークダウン表示になっていることを確認出来れば完了。

**Comment by tominagashuji** [comment]
article_controller の create 処理にして article レコードを作成する。しかし上手くいかない。
作り方は、agenda を元に作成（build）していくが、 agenda_id , user_id , team_id が必要な様子。→適当にidを埋めたら出来た！
埋めたら article の show 画面の表示だが、マークダウンになっていない様子。。
そもそもマークダウンについて調べて内容を忘れたのでもう一度調査しよう。

**Comment by tominagashuji** [comment]
改めてrubocopも落ち着いたので再度プルリクを出して行こう！
